import Link from 'next/link';
import { Camera, MonitorPlay, QrCode, Library } from 'lucide-react';

export default function DashboardPage() {
  const demoEventId = "demo-wedding";

  return (
    <div className="min-h-screen bg-neutral-50 p-8 font-sans">
      <div className="max-w-5xl mx-auto">
        <header className="mb-12">
          <Link href="/" className="text-neutral-500 hover:text-neutral-900 transition-colors mb-2 inline-block">
            &larr; Back home
          </Link>
          <h1 className="text-4xl font-bold tracking-tight text-neutral-900">Event Dashboard (MVP)</h1>
          <p className="text-neutral-500 mt-2 text-lg">Manage your Memoire interactive setups for the venue.</p>
        </header>

        <div className="grid md:grid-cols-3 gap-6">
          {/* Capture Setup Card */}
          <div className="bg-white rounded-2xl p-8 border border-neutral-200 shadow-sm flex flex-col items-start">
            <div className="p-3 bg-neutral-100 rounded-xl mb-6">
              <Camera className="w-8 h-8 text-neutral-700" />
            </div>
            <h2 className="text-2xl font-bold text-neutral-900 mb-2">Guest Booth</h2>
            <p className="text-neutral-500 mb-8 flex-1 text-sm">
              Run this on an iPad or tablet at the venue. Guests will use this interface to snap and submit photos.
            </p>
            <Link 
              href={`/capture/${demoEventId}`}
              className="inline-flex items-center justify-center w-full px-6 py-3 bg-neutral-900 text-white rounded-xl font-medium hover:bg-neutral-800 transition-colors"
            >
              Launch Capture App
            </Link>
          </div>

          {/* Projection Setup Card */}
          <div className="bg-white rounded-2xl p-8 border border-neutral-200 shadow-sm flex flex-col items-start">
            <div className="p-3 bg-neutral-100 rounded-xl mb-6">
              <MonitorPlay className="w-8 h-8 text-neutral-700" />
            </div>
            <h2 className="text-2xl font-bold text-neutral-900 mb-2">Live Wall</h2>
            <p className="text-neutral-500 mb-8 flex-1 text-sm">
              Connect this screen to a projector. Photos will appear in real-time as they are submitted by guests.
            </p>
            <Link 
              href={`/projection/${demoEventId}`}
              className="inline-flex items-center justify-center w-full px-6 py-3 bg-white text-neutral-900 border border-neutral-300 rounded-xl font-medium hover:bg-neutral-50 transition-colors"
            >
              Launch Projection Server
            </Link>
          </div>
          
          {/* Management Card */}
          <div className="bg-white rounded-2xl p-8 border border-neutral-200 shadow-sm flex flex-col items-start">
            <div className="p-3 bg-neutral-100 rounded-xl mb-6">
              <Library className="w-8 h-8 text-neutral-700" />
            </div>
            <h2 className="text-2xl font-bold text-neutral-900 mb-2">Gallery & Stats</h2>
            <p className="text-neutral-500 mb-8 flex-1 text-sm">
              View all captured moments, track engagement statistics, and moderate the live feed.
            </p>
            <Link 
              href={`/dashboard/${demoEventId}`}
              className="inline-flex items-center justify-center w-full px-6 py-3 bg-emerald-50 text-emerald-700 border border-emerald-200 rounded-xl font-medium hover:bg-emerald-100 transition-colors"
            >
              Open Gallery View
            </Link>
          </div>
        </div>

        <div className="mt-12 bg-neutral-100 rounded-2xl p-8 border border-neutral-200">
          <h3 className="text-xl font-bold text-neutral-900 mb-2 flex items-center gap-2">
            <QrCode className="w-5 h-5" /> How the MVP Works
          </h3>
          <ul className="list-disc list-inside text-neutral-600 space-y-2 mt-4">
            <li>Open the <strong>Capture App</strong> in one window/device.</li>
            <li>Open the <strong>Projection Screen</strong> in another window.</li>
            <li>Take a photo in the Capture App and submit it.</li>
            <li>Watch it instantly appear on the Projection Screen with an animation.</li>
            <li>Scan the QR code generated by the Capture app to download the image.</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
